# Production environment override
services:
  php:
    build:
      context: .
      target: frankenphp_prod
    environment:
      SERVER_NAME: http://localhost:8080
    # volumes:
    #   - ./:/app
    ports:
      - "127.0.0.1:8080:8080"
